//
//  ShareExportService.swift
//  BillSplitz
//

import Foundation

struct ShareExportService {
    func plainTextSummary(draft: SplitDraft, settlementLines: [SettlementLine]) -> String {
        let currencyCode = draft.session.currencyCode
        let participantByID = Dictionary(uniqueKeysWithValues: draft.participants.map { ($0.id, $0) })
        let payerName = draft.payer?.name ?? "the payer"

        var lines: [String] = []
        lines.append(draft.session.title)
        lines.append("Paid by \(payerName)")
        lines.append("Receipt total: \(CurrencyFormatter.string(for: draft.receiptTotal, currencyCode: currencyCode))")
        lines.append("")
        lines.append("Who owes what")

        for settlementLine in settlementLines {
            guard let participant = participantByID[settlementLine.participantID] else {
                continue
            }

            var row = "\(participant.name): \(CurrencyFormatter.string(for: settlementLine.grandTotal, currencyCode: currencyCode))"
            if let handle = participant.paymentHandle, !handle.isEmpty {
                row += " (\(handle))"
            }
            lines.append(row)
        }

        lines.append("")
        lines.append("Breakdown")
        for settlementLine in settlementLines {
            guard let participant = participantByID[settlementLine.participantID] else {
                continue
            }

            lines.append(
                "\(participant.name): items \(CurrencyFormatter.string(for: settlementLine.itemSubtotal, currencyCode: currencyCode)), tax \(CurrencyFormatter.string(for: settlementLine.taxShare, currencyCode: currencyCode)), tip \(CurrencyFormatter.string(for: settlementLine.tipShare, currencyCode: currencyCode))"
            )
        }

        lines.append("")
        lines.append("Generated by BillSplitz")
        return lines.joined(separator: "\n")
    }
}
